version: '3.3'

services:
  backend:
    restart: always
    build: ./backend
    container_name: backend
    ports:
      - 2000:2000
    depends_on: 
     - db
  db:
    image: postgres:13.4
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: docker_test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
